<a href="https://colab.research.google.com/github/claudio1804-12/Telecom2/blob/main/Telecom2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [22]:
import pandas as pd
url = 'https://raw.githubusercontent.com/claudio1804-12/Telecom2/refs/heads/main/df_norm.csv'
df = pd.read_csv(url)
df.head()

,customerID,Churn,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,...,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,Charges.Monthly,Charges.Total
0,0002-ORFBO,No,Female,0,Yes,Yes,9,Yes,No,DSL,...,Yes,No,Yes,Yes,No,One year,Yes,Mailed check,65.6,593.30
1,0003-MKNFE,No,Male,0,No,No,9,Yes,Yes,DSL,...,No,No,No,No,Yes,Month-to-month,No,Mailed check,59.9,542.40
2,0004-TLHLJ,Yes,Male,0,No,No,4,Yes,No,Fiber optic,...,No,Yes,No,No,No,Month-to-month,Yes,Electronic check,73.9,280.85
3,0011-IGKFF,Yes,Male,1,Yes,No,13,Yes,No,Fiber optic,...,Yes,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,98.0,1237.85
4,0013-EXCHZ,Yes,Female,1,Yes,No,3,Yes,No,Fiber optic,...,No,No,Yes,Yes,No,Month-to-month,Yes,Mailed check,83.9,267.40

In [23]:
df=df.drop('customerID', axis=1)

In [24]:
df_corr = df[['Charges.Total','tenure','Charges.Monthly','SeniorCitizen']]
df_corr.corr()

                 Charges.Total    tenure  Charges.Monthly  SeniorCitizen
Charges.Total         1.000000  0.826178         0.651174       0.103006
tenure                0.826178  1.000000         0.247900       0.016567
Charges.Monthly       0.651174  0.247900         1.000000       0.220173
SeniorCitizen         0.103006  0.016567         0.220173       1.000000

In [25]:
df = df.drop(['tenure','Charges.Monthly'], axis=1)
df.head()

,Churn,gender,SeniorCitizen,Partner,Dependents,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,Charges.Total
0,No,Female,0,Yes,Yes,Yes,No,DSL,No,Yes,No,Yes,Yes,No,One year,Yes,Mailed check,593.30
1,No,Male,0,No,No,Yes,Yes,DSL,No,No,No,No,No,Yes,Month-to-month,No,Mailed check,542.40
2,Yes,Male,0,No,No,Yes,No,Fiber optic,No,No,Yes,No,No,No,Month-to-month,Yes,Electronic check,280.85
3,Yes,Male,1,Yes,No,Yes,No,Fiber optic,No,Yes,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,1237.85
4,Yes,Female,1,Yes,No,Yes,No,Fiber optic,No,No,No,Yes,Yes,No,Month-to-month,Yes,Mailed check,267.40

In [26]:
from sklearn.preprocessing import OneHotEncoder
df_encode = OneHotEncoder(sparse=False)
df_encode = encoder.fit_transform(df[["Churn_no","Contrato"]])

,SeniorCitizen,Charges.Total,Churn_No,Churn_Yes,gender_Female,gender_Male,Partner_No,Partner_Yes,Dependents_No,Dependents_Yes,...,StreamingMovies_Yes,Contract_Month-to-month,Contract_One year,Contract_Two year,PaperlessBilling_No,PaperlessBilling_Yes,PaymentMethod_Bank transfer (automatic),PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,0,593.30,True,False,True,False,False,True,False,True,...,False,False,True,False,False,True,False,False,False,True
1,0,542.40,True,False,False,True,True,False,True,False,...,True,True,False,False,True,False,False,False,False,True
2,0,280.85,False,True,False,True,True,False,True,False,...,False,True,False,False,False,True,False,False,True,False
3,1,1237.85,False,True,False,True,False,True,True,False,...,True,True,False,False,False,True,False,False,True,False
4,1,267.40,False,True,True,False,False,True,True,False,...,False,True,False,False,False,True,False,False,False,True